meta_product_name: "Bigger Or Better"
meta_title: "Bigger Or Better - Trade your stuff"
meta_description: "Don't throw out your stuff! Trade it for something bigger or better."
meta_image: "app/assets/images/cover.png"`
